### ISSUE TITLE
correct GPIO definitions in caravel.h

### ISSUE THREAD

**Issue by jeffdi** [efabless/caravel_mgmt_soc_litex#53]
PU/PD defintions are incorrect.  Ensure defs.h does not replicate these definitions.

**Comment by RTimothyEdwards** [comment]
This has been corrected but this issue needs to be linked to a pull request.

**Comment by azwefabless** [comment]
Needs documentation to close

**Comment by jeffdi** [comment]
commit correcting issue is ae92b99c17c4014daeff3021656ec19fecacb1e6
